# Generated by Django 5.2.8 on 2025-11-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_see_all_events', 'Може переглядати всі події'), ('can_edit_all_events', 'Може редагувати всі події')], 'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
    ]
