# Generated by Django 5.2.8 on 2025-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Виконано'),
        ),
    ]
