# Generated by Django 5.2.8 on 2025-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='created', max_length=50, verbose_name='Дія')),
                ('model', models.CharField(max_length=90, verbose_name='Модель')),
                ('object_id', models.IntegerField(verbose_name='ID обʼєкту')),
            ],
        ),
    ]
