# Generated by Django 5.2.8 on 2026-01-23 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category'),
        ),
    ]
