# Generated by Django 5.2.8 on 2025-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=140, verbose_name='Короткий опис'),
        ),
    ]