# Generated by Django 5.2.8 on 2025-11-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendaruser',
            options={'permissions': [('can_set_user_permissions', 'Може додавати дозволи користувачеві'), ('can_see_user_permissions', 'Може переглядати список дозволів користувача')], 'verbose_name': 'Calendar user', 'verbose_name_plural': 'Calendar users'},
        ),
    ]
