# Generated by Django 5.2.8 on 2025-11-18 18:34

from django.db import migrations
from django.contrib.auth.models import Permission
# from django.contrib.contenttypes.models import ContentType


# content_type_global, _ = ContentType.objects.get_or_create(app_label='calendar_accounts', model='global')

# def create_custom_permissions(apps, schema_editor):
#     Permission.objects.create(
#         codename='can_manage_calendar',
#         name='Може керувати календарем',
#         content_type=content_type_global
#     )
#     Permission.objects.create(
#         codename='can_manage_users',
#         name='Може керувати користувачами',
#         content_type=content_type_global
#     )

# def rollback_permissions(apps, schema_editor):
#     Permission.objects.filter(
#         content_type=content_type_global,
#         codename__in=['can_manage_calendar', 'can_manage_users']
#     ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('calendar_accounts', '0002_alter_calendaruser_options'),
    ]

    operations = [
        # migrations.RunPython(
        #     code=create_custom_permissions,
        #     reverse_code=rollback_permissions
        # )
    ]
