# Generated by Django 5.2.8 on 2026-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_accounts', '0003_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendaruser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
