# Generated by Django 5.2.8 on 2026-01-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_accounts', '0004_calendaruser_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
